[default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
#remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]   # a list of remappings

# See more config options https://github.com/foundry-rs/foundry/tree/master/config